server:
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#      exclude: classpath://static/**,/**
  management:
    endpoints:
      web:
        exposure:
          include: "*"
        cors:
          allowed-origins: "*"
          allowed-methods: "*"
# pagehelper properties
pagehelper:
  helperDialect: mysql
#  分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
#  支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。 使用方法可以参考测试代码中的 com.github.pagehelper.test.basic 包下的 ArgumentsMapTest 和 ArgumentsObjTest。
  supportMethodsArguments: true
  params:
    count: countSql
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB